### ISSUE TITLE
Wrong intrinsic value check

### ISSUE THREAD

**Issue by omdv** [marcdemers/py_vollib_vectorized#1]
Hello, thanks for the library!

My use case is to use your library to do a fast greek calculations on a dataframe with options of **different** underlyings and expirations. Below is the specific case with actual prices (today's close) for four different contracts:

```
import pandas as pd
import numpy as np
import py_vollib
import py_vollib_vectorized

flag = ['p', 'p', 'c', 'c']
option_prices = [3.72, 1.75, 5.30, 45.70]
under_prices = [127.14, 88.21, 107.96, 107.96]
strikes = [122, 87.5, 114.21, 69.21]
dtes = [0.065, 0.008, 0.085, 0.909]
r = np.array([0.25])

option_price = py_vollib_vectorized.implied_volatility.vectorized_implied_volatility(
    option_prices,
    under_prices,
    strikes,
    dtes,
    r,
    flag,
    on_error='warn',
    return_as='series') 

option_price
```

I am getting the warning on intrinsic value:

```
/opt/miniconda3/lib/python3.7/site-packages/py_vollib_vectorized/implied_volatility.py:76: UserWarning: Found Below Intrinsic contracts at index [3]
  below_intrinsic, above_max_price = _check_below_and_above_intrinsic(K, F, flag, undiscounted_option_price, on_error)

0    0.532017
1    0.690998
2    0.552891
3         NaN
Name: IV, dtype: float64
```

The basic check shows that it should be OK.
Fourth line is a deep ITM option with ~0.9 delta, and 45.70+69.21 > 107.96.

I skimmed through the code and unless I am missing something the line 55 in [this file](https://github.com/marcdemers/py_vollib_vectorized/blob/0847cf6bd5ce5ee15e5dae3ee12e7bca1e34df1b/py_vollib_vectorized/util/data_format.py) shouldn't have `np.any`?

**Comment by omdv** [comment]
Alright, this can be closed. I didn't read py_vollib documentation clearly. Now I can see that it is [limited to European style options](https://github.com/vollib/py_vollib/issues/7).

**Comment by phenn52** [comment]
Is there a way to modify the package to try/except the below intrinsic warning so that the IV output will be equal to np.nan or zero?

I am thinking about a fix along what was outlined here but cannot figure out how to apply this fix to the vectorized py_vollib package.

[https://github.com/vollib/py_vollib/issues/14#issuecomment-615875343](url)

**Comment by marcdemers** [comment]
@phenn52  your link does not work

**Comment by phenn52** [comment]
> @phenn52 your link does not work

Hi Marc - thanks for letting me know. This link should work now

[https://github.com/vollib/py_vollib/issues/14#issuecomment-615875343](https://github.com/vollib/py_vollib/issues/14#issuecomment-615875343)

**Comment by omdv** [comment]
@phenn52 , I am not the author, but I don't understand your question. The example I posted at the beginning does not raise exception, it is just the warning, the returned IV is `np.nan` already. The problem is that does not work for deep-ITM options in my case. If it works for you - great, you can use it as-is, I believe.

**Comment by marcdemers** [comment]
@omdv  How did you calculate the 0.909 DTE for your fourth contract?

**Comment by marcdemers** [comment]
@phenn52 The above and below intrinsic should already be `np.nan`, can you provide a reproducible example where they are not?

**Comment by omdv** [comment]
@marcdemers , Hey. Thanks for your question. While answering it I actually realized where my mistake is and that there is nothing wrong with the library. I used 0.25 for `risk-free interest rate`, for some reason wrongly assuming that the units are percentages. Once I switched to `0.0025` everything worked well. Of course with 25% of annual interest one year expiration deep ITM option was not passing the intrinsic value check. Thanks again, I started looking at other more complex libraries, but this will work very well.

Below is how I calculate DTE - basically time till settlement normalized by 365 days. Makes sense?
```
expiration = pd.to_datetime(df['lastTradeDateOrContractMonth']+'T23:59:59', errors='raise').dt.tz_localize(tz='US/Eastern')
df['dte'] = (expiration - dt.datetime.now(tz=pytz.timezone('US/Eastern'))) / pd.Timedelta('365 days')
```

Below are some results after I fixed the interest rate.
IV values:
```
0     0.538346
1     0.572795
2     0.645408
3     0.487533
4     0.472895
5     0.579759
6     0.576731
7     0.736465
8     0.924884
9     0.407187
10    1.349943
11    0.479478
12    0.338534
Name: iv, dtype: float64
```

deltas:
```
0    -0.078479
1     0.445258
2     0.859731
3     0.497690
4     0.124825
5     0.852474
6     0.815045
7    -0.246076
8    -0.267806
9     0.501942
10   -0.221046
11   -0.016002
12   -0.054273
```

I didn't yet do detailed comparison but just a quick glance tells me that it is very close to deltas from my broker UI. The bottom two expiring tomorrow and deltas seems to be a bit too high - but I think I know the reason.

**Comment by marcdemers** [comment]
> @marcdemers , Hey. Thanks for your question. While answering it I actually realized where my mistake is and that there is nothing wrong with the library. I used 0.25 for `risk-free interest rate`, for some reason wrongly assuming that the units are percentages. Once I switched to `0.0025` everything worked well. Of course with 25% of annual interest one year expiration deep ITM option was not passing the intrinsic value check. Thanks again, I started looking at other more complex libraries, but this will work very well.
> 
> Below is how I calculate DTE - basically time till settlement normalized by 365 days. Makes sense?
> 
> ```
> expiration = pd.to_datetime(df['lastTradeDateOrContractMonth']+'T23:59:59', errors='raise').dt.tz_localize(tz='US/Eastern')
> df['dte'] = (expiration - dt.datetime.now(tz=pytz.timezone('US/Eastern'))) / pd.Timedelta('365 days')
> ```
> 
> Below are some results after I fixed the interest rate.
> IV values:
> 
> ```
> 0     0.538346
> 1     0.572795
> 2     0.645408
> 3     0.487533
> 4     0.472895
> 5     0.579759
> 6     0.576731
> 7     0.736465
> 8     0.924884
> 9     0.407187
> 10    1.349943
> 11    0.479478
> 12    0.338534
> Name: iv, dtype: float64
> ```
> 
> deltas:
> 
> ```
> 0    -0.078479
> 1     0.445258
> 2     0.859731
> 3     0.497690
> 4     0.124825
> 5     0.852474
> 6     0.815045
> 7    -0.246076
> 8    -0.267806
> 9     0.501942
> 10   -0.221046
> 11   -0.016002
> 12   -0.054273
> ```
> 
> I didn't yet do detailed comparison but just a quick glance tells me that it is very close to deltas from my broker UI. The bottom two expiring tomorrow and deltas seems to be a bit too high - but I think I know the reason.

@omdv  Good catch ;) everything looks good here, good luck with your projects!

**Comment by Geek4ray** [comment]
> @marcdemers , Hey. Thanks for your question. While answering it I actually realized where my mistake is and that there is nothing wrong with the library. I used 0.25 for `risk-free interest rate`, for some reason wrongly assuming that the units are percentages. Once I switched to `0.0025` everything worked well. Of course with 25% of annual interest one year expiration deep ITM option was not passing the intrinsic value check. Thanks again, I started looking at other more complex libraries, but this will work very well.
> 
> Below is how I calculate DTE - basically time till settlement normalized by 365 days. Makes sense?
> 
> ```
> expiration = pd.to_datetime(df['lastTradeDateOrContractMonth']+'T23:59:59', errors='raise').dt.tz_localize(tz='US/Eastern')
> df['dte'] = (expiration - dt.datetime.now(tz=pytz.timezone('US/Eastern'))) / pd.Timedelta('365 days')
> ```
> 
> Below are some results after I fixed the interest rate. IV values:
> 
> ```
> 0     0.538346
> 1     0.572795
> 2     0.645408
> 3     0.487533
> 4     0.472895
> 5     0.579759
> 6     0.576731
> 7     0.736465
> 8     0.924884
> 9     0.407187
> 10    1.349943
> 11    0.479478
> 12    0.338534
> Name: iv, dtype: float64
> ```
> 
> deltas:
> 
> ```
> 0    -0.078479
> 1     0.445258
> 2     0.859731
> 3     0.497690
> 4     0.124825
> 5     0.852474
> 6     0.815045
> 7    -0.246076
> 8    -0.267806
> 9     0.501942
> 10   -0.221046
> 11   -0.016002
> 12   -0.054273
> ```
> 
> I didn't yet do detailed comparison but just a quick glance tells me that it is very close to deltas from my broker UI. The bottom two expiring tomorrow and deltas seems to be a bit too high - but I think I know the reason.

Hi @omdv, Can you please confirm if this is still working fine for you, for deep ITM contracts, is the iv calculation right?


Because in my setup, it gives np.nan for iv of DEEP ITM contracts

**Comment by Geek4ray** [comment]
Have I wrongly installed llvm?

**Comment by rajnishdahiya** [comment]
I do see deep ITM option prices are indeed below intrinsic at times, e.g. I get below warning. Various indices are minute wise time series of a deep ITM
`/mnt/c/Users/csera/Desktop/temp/5-swans/code/trade_utils/apps/.venv/lib/python3.10/site-packages/py_vollib_vectorized/implied_volatility.py:75: UserWarning: Found Below Intrinsic contracts at index [134, 142, 145, 146, 148, 150, 153, 155, 157, 159, 161, 163, 165, 167, 169, 170, 173, 175, 179, 181, 183, 184, 337, 338, 340, 353, 356, 358, 360, 362, 364, 367, 368, 371, 373, 375, 377, 379, 380, 382, 384, 386, 389, 391, 393, 394, 397, 399, 400, 403, 404, 406, 408, 411, 413, 414, 416, 418, 420, 422, 425, 426, 429, 431, 432, 434, 437, 439, 441, 443, 445, 447, 449, 451, 453, 455, 457, 458, 461, 463, 464, 466, 469, 471, 472, 474, 476, 479, 481, 482, 484, 487, 489, 490, 492, 494, 497, 498, 500, 503, 504, 506, 508, 510, 513, 515, 517, 518, 520, 522, 524, 527, 529, 531, 532, 534, 536, 539, 541, 543, 545, 547, 548, 550, 553, 554, 557, 559, 561, 562, 565, 566, 568, 571, 573, 574, 577, 578, 580, 582, 584, 586, 588, 591, 593, 594, 597, 598, 600, 602, 604, 606, 609, 610, 613, 615, 617, 618, 620, 622, 625, 627, 628, 631, 632, 634, 636, 638, 641, 643, 644, 647, 648, 650, 652, 655, 657, 661, 664, 667, 669, 673, 674, 678, 680, 683, 685, 687, 688, 690, 693, 695, 696, 699, 700, 702, 704, 707, 708, 710, 712, 715, 716, 719, 721, 723, 725, 727, 729, 730, 733, 735, 737, 739, 740]
  below_intrinsic, above_max_price = _check_below_and_above_intrinsic(K, F, flag, undiscounted_option_price, on_error)`
 
 and it's okay if IV for them comes out to be 0 or NaN, but in this case I am getting NaN for all other time points as well. If I calculate for a particular point in time I get correct values, but when doing for entire series in vectorized fashion I get all NaNs. Is it expected?
