### ISSUE TITLE
Alternative handling for when price is below/above intrinsic

### ISSUE THREAD

**Issue by richy1996** [marcdemers/py_vollib_vectorized#12]
What's a good way to return something other than nan for implied vol when price is below/above intrinsic value? Something like 0 for too low and inf for too high.

**Comment by marcdemers** [comment]
there's no value to be returned, because the iv is undefined in that scenario

**Comment by richy1996** [comment]
As a workaround, I calculated a "fair" value using an arbitrary sigma. Then for every price that has implied_vol as nan, I compare the mkt price to the fair, if mkt < fair, put 0 for implied, else 1e3 or something big. 

I get your point with no value to be returned but occasionally mkt prices are off and I needed some way to distinguish between the extreme highs/lows.

Great package!

**Comment by jhirschibar** [comment]
Related to this issue but different, the `vectorized_implied_volatility` functions have a way to specify what to do `on_error` when the options price is to high or low. However, the `price_dataframe` api function does not have a way to pass this through, leaving the user with the default `warn` option only. I'd like to pass `ignore` at times. Can this be added?
