### ISSUE TITLE
vectorized_delta doesn't call numerical_delta_black correctly

### ISSUE THREAD

**Issue by m1jkf00** [marcdemers/py_vollib_vectorized#3]
Thank you for this package!

When I try to calculate Black deltas using vectorized_delta, it returns an error that numerical_delta_black was passed an unexpected bs argument. I've patched this in my versions of the file by just adding "bs" as an argument to the numerical function, though it probably would have been better to stop greeks.delta from passing the bs argument in the first place.

**Comment by marcdemers** [comment]
Hi @m1jkf00 , thanks for the bug report. I will fix this in a new version. I kept the delta functions' signatures standardized, which is why I still pass the "bs" arguments to black model.

**Comment by ccagrawal** [comment]
I'm sure you are aware, but the same is true for the other greeks (e.g. numerical_vega_black and numerical_gamma_black).

**Comment by marcdemers** [comment]
resolved by https://github.com/marcdemers/py_vollib_vectorized/pull/20
