### ISSUE TITLE
Theta values differ significantly between py_vollib and py_vollib_vectorized

### ISSUE THREAD

**Issue by dmastylo** [marcdemers/py_vollib_vectorized#5]
```
In [13]: 
    ...: from py_vollib.black_scholes.greeks.analytical import delta, gamma, theta, vega, rho
    ...: 
    ...: vollib_option_args = {
    ...:     "sigma": 2.321860179778894,
    ...:     "S": 37.34,
    ...:     "K": 15,
    ...:     "r": 0,
    ...:     "t": (8.013952981782408 / 365),
    ...:     "flag": "c",
    ...: }
    ...: vollib_results = theta(**vollib_option_args)
    ...: print("standard vollib theta", vollib_results)
    ...: 
    ...: df_2 = pd.DataFrame()
    ...: 
    ...: df_2['Flag'] = ["c"]
    ...: df_2['S'] = ["37.34"]
    ...: df_2['K'] = ["15"]
    ...: df_2['T'] = [8.013952981782408 / 365]
    ...: df_2['R'] = [0]
    ...: df_2['adjusted_mark'] = [22.35]
    ...: 
    ...: vectorized_results = price_dataframe(
    ...:     df_2,
    ...:     flag_col='Flag',
    ...:     underlying_price_col='S',
    ...:     strike_col='K',
    ...:     annualized_tte_col='T',
    ...:     riskfree_rate_col='R',
    ...:     #sigma_col='IV',
    ...:     price_col='adjusted_mark',
    ...:     model='black_scholes',
    ...:     inplace=False
    ...: )
    ...: print("vectorized IV", vectorized_results["IV"])
    ...: print("vectorized theta", vectorized_results["theta"])
    ...: 
standard vollib theta -0.00594883586530434
vectorized IV 0    2.32186
Name: IV, dtype: float64
vectorized theta 0   -0.00488
Name: theta, dtype: float64
```

As you can see the sigma/IV values are the same, but theta differs quite a bit. The difference becomes more pronounced as DTE gets closer to 0 or the option becomes more ITM.

I've seen these discrepancies primarily on:
* very short DTE (options expiring today), regardless of money-ness or put/call type
* ITM options with longer DTE (I've seen it on 8-29 DTE options)

Happy to show more examples if you'd like

**Comment by marcdemers** [comment]
Hey, thanks for using the package.
This is due to the fact that you're using py_vollib's analytical greeks.
The following code gives the right output (note the package import from py_vollib).

```
import pandas as pd
from py_vollib_vectorized import price_dataframe
from py_vollib.black_scholes.greeks.numerical import delta, gamma, theta, vega, rho

vollib_option_args = {
    "sigma": 2.321860179778894,
    "S": 37.34,
    "K": 15,
    "r": 0,
    "t": (8.013952981782408 / 365),
    "flag": "c",
}
vollib_results = theta(**vollib_option_args)
print("standard vollib theta", vollib_results)

df_2 = pd.DataFrame()

df_2['Flag'] = ["c"]
df_2['S'] = ["37.34"]
df_2['K'] = ["15"]
df_2['T'] = [8.013952981782408 / 365]
df_2['R'] = [0]
df_2['adjusted_mark'] = [22.35]

vectorized_results = price_dataframe(
    df_2,
    flag_col='Flag',
    underlying_price_col='S',
    strike_col='K',
    annualized_tte_col='T',
    riskfree_rate_col='R',
    #sigma_col='IV',
    price_col='adjusted_mark',
    model='black_scholes',
    inplace=False
)
print("vectorized IV", vectorized_results["IV"])
print("vectorized theta", vectorized_results["theta"])
```

gives the output:

```
standard vollib theta      theta
0 -0.00488
vectorized IV 0    2.32186
Name: IV, dtype: float64
vectorized theta 0   -0.00488
Name: theta, dtype: float64

```

The phenomenon you're describing is because as TTE gets closer to zero, numerical approximation methods are less accurate than analytical (exact) methods.

Once my schedule clears, I'll implement analytical greek calculations in the library.

-Marc

**Comment by dmastylo** [comment]
Got it, thank you so much for this package, it's immensely useful. What is involved in the lift to get analytical greek calculations in the library, does it require a lot of domain knowledge?

**Comment by marcdemers** [comment]
I haven't looked into it too deeply yet, but it mostly revolves around finding ways to implement the calculation of the normal distribution's cdf and pdf into numba-accepted functions, such that the analytical computation of the black/black scholes greeks is fast.

You're more than welcome to give it a shot and submit an (even partial) PR! :)

Note that this doesn't mean the numerical greeks are "wrong" per se. Options pricing is inherently a difficult task (some dedicate their life to the problem..), and black scholes is only one such model -- it has no inherent truth and makes various assumptions about risk, distribution of returns, etc.

**Comment by dmastylo** [comment]
> I haven't looked into it too deeply yet, but it mostly revolves around finding ways to implement the calculation of the normal distribution's cdf and pdf into numba-accepted functions, such that the analytical computation of the black/black scholes greeks is fast.
> 
> You're more than welcome to give it a shot and submit an (even partial) PR! :)
> 
> Note that this doesn't mean the numerical greeks are "wrong" per se. Options pricing is inherently a difficult task (some dedicate their life to the problem..), and black scholes is only one such model -- it has no inherent truth and makes various assumptions about risk, distribution of returns, etc.

Got it. Unfortunately, my domain knowledge in the actual programmatic implementation of options pricing models makes my head spin a bit (definitely was when I was digging into the source here) and I would probably get nowhere fast. Otherwise I would love to help. 

And yes, understood on the modeling; I just wasn't even aware until you flagged it to me that vollib had two different versions of the greek calculation. The approximations are mostly good enough for now, I may just flag my datasets generated on the particularly suspect ones. Thanks again for your quick responses and your help, much appreciate your work here.

**Comment by RedDevil-Slayer** [comment]
Hey @marcdemers have you had a chance to fix the library to implement analytical greek calculations? As I am mainly working with options that are close to expiry, so my thetas are quite inaccurate. 
Unfortunately I don't have the programming capability to try and implement it myself. Would be amazing if you could implement the analytical methods.
