### ISSUE TITLE
ModuleNotFoundError: No module named '_testcapi'

### ISSUE THREAD

**Issue by jenish99** [marcdemers/py_vollib_vectorized#7]
Facing same error which is problem of main py_vollib module. Any solution to this?

    from _testcapi import DBL_MIN, DBL_MAX
ModuleNotFoundError: No module named '_testcapi'

**Comment by marcdemers** [comment]
Can you provide a reproducible example and your python version? And the stacktrace of this error

**Comment by jenish99** [comment]
python version 3.9.6.

Tried example code. But problem is with original py_vollib module I guess.
Attached is the python code.

[Option_greeks.txt](https://github.com/marcdemers/py_vollib_vectorized/files/7061684/Option_greeks.txt)

**Comment by marcdemers** [comment]
Your code sample does not use this library.
